# .streamlit/config.toml
[theme]
base="light"
primaryColor="#0b44bc"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f7f7f7"
textColor="#262730"
font="sans serif"

[server]
headless = true
enableCORS = false
